stages:
  - build
  - verification

before_script:
  - export DEVELOPER_DIR=/Applications/Xcode12.2.app/Contents/Developer

# Builds the library with the release configuration
build-release:
  stage: build
  script:
    - xcodebuild -configuration Release -arch arm64
  artifacts:
    expire_in: 2 weeks
    when: always
    paths:
      - build/*/*.a
  tags:
    - xcode12.2

# Tests the library
test:
  stage: verification
  script:
    - xcodebuild build-for-testing -scheme ProximityNotificationTests -destination 'platform=iOS Simulator,name=iPhone 12' 
    - xcodebuild test -scheme ProximityNotificationTests -destination 'platform=iOS Simulator,name=iPhone 12' 
  tags:
    - xcode12.2

